# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Reproach"
license = "MIT"
licenselink = "https://github.com/dg01d/reproach/blob/master/LICENSE.md"
description = "Hugo Templates are driving me mad, so I decided to create my own."
homepage = "https://ascraeus.org/"
tags = ["barebone", "brutal"]
features = ["none", "twittercards", "skeleton", "svg"]
min_version = 0.18

[author]
  name = "Daniel Goldsmith"
  homepage = "https://ascraeus.org"
